services:
  arr-watch:
    image: ghcr.io/carlosj188/arr-watch:1.0.9   # ou :latest
    container_name: arr-watch
    restart: unless-stopped
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
