services:
  arrpulse:
    image: ghcr.io/carlosj188/arrpulse:latest   # ou fixe uma versão: :1.0.9
    container_name: arrpulse
    restart: unless-stopped
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
